version: 0.0
os: linux
files:
  - source: ./springboot-crud-api-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user
ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 700
      runas: root


# version: 0.0
# os: linux
# files:
# - source: /
#   destination: /home/ec2-user
# hooks:
#   AfterInstall:
#   - location: scripts/fix_previleges.sh
#     timeout: 300
#     runas: root
#   ApplicationStart:
#   - location: scripts/start_server.sh
#     timeout: 300
#     runas: root
#   ApplicationStop:
#   - location: scripts/stop_server.sh
#     timeout: 300
#     runas: root
